#' Washington SARS-CoV-2 Genealogy
#'
#' This dataset is a \code{phylo} object of a genealogy generated by BEAST from
#' the sequence data in Medina, et al. 2024.
#'
#' C. M. Medina, J. A. Palacios, V. M. Minin (2024). Accounting for reporting 
#' delays in real-time phylodynamic analyses with preferential sampling. 
#' TODO: Update with paper location
#'
#' @source <https://doi.org/10.55876/gis8.240619zd> 
"washington_genealogy"